MATH_TRAINING_MATERIALS = 'Материалы для подготовки к экзамену по математике:'
PREVIOUS_TASKS_EXAMPLES = 'Задания прошлых лет'
LINAL = 'Линал'
MATH_AN = 'Матан'
PROB_THEORY = 'Теорвер'
STATS = 'Матстат'
DIFF_EQUATIONS = 'Диффуры'
LINKS_FILE_NAME = 'links'